/*
 * // Copyright (c) Radzivon Bartoshyk 6/2026. All rights reserved.
 * //
 * // Redistribution and use in source and binary forms, with or without modification,
 * // are permitted provided that the following conditions are met:
 * //
 * // 1.  Redistributions of source code must retain the above copyright notice, this
 * // list of conditions and the following disclaimer.
 * //
 * // 2.  Redistributions in binary form must reproduce the above copyright notice,
 * // this list of conditions and the following disclaimer in the documentation
 * // and/or other materials provided with the distribution.
 * //
 * // 3.  Neither the name of the copyright holder nor the names of its
 * // contributors may be used to endorse or promote products derived from
 * // this software without specific prior written permission.
 * //
 * // THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * // AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * // IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * // DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * // FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * // DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * // SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * // CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * // OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * // OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#[rustfmt::skip]
pub(crate) static ZIGZAG: [(usize, usize); 64] = [
    (0,0),(1,0),(0,1),(2,0),(1,1),(0,2),(3,0),(2,1),
    (1,2),(0,3),(3,1),(2,2),(1,3),(3,2),(2,3),(3,3),
    (4,0),(5,0),(4,1),(6,0),(5,1),(4,2),(7,0),(6,1),
    (5,2),(4,3),(7,1),(6,2),(5,3),(7,2),(6,3),(7,3),
    (0,4),(1,4),(0,5),(2,4),(1,5),(0,6),(3,4),(2,5),
    (1,6),(0,7),(3,5),(2,6),(1,7),(3,6),(2,7),(3,7),
    (4,4),(5,4),(4,5),(6,4),(5,5),(4,6),(7,4),(6,5),
    (5,6),(4,7),(7,5),(6,6),(5,7),(7,6),(6,7),(7,7),
];

/// HEVC up-right diagonal scan for a single 4×4 block, `(row, col)`.
#[rustfmt::skip]
pub(crate) static DIAG_SCAN_4X4: [(usize, usize); 16] = [
    (0,0),(1,0),(0,1),(2,0),(1,1),(0,2),(3,0),(2,1),
    (1,2),(0,3),(3,1),(2,2),(1,3),(3,2),(2,3),(3,3),
];

/// HEVC sub-block-major up-right diagonal scan for a 16×16 TU, `(row, col)`.
/// Layout matches the 8×8 `ZIGZAG`: a 4×4 grid of 4×4 sub-blocks, each sub-block
/// scanned by `DIAG_SCAN_4X4`, the sub-blocks themselves visited in up-right
/// diagonal order. Generated by the same construction that reproduces `ZIGZAG`
/// and `DIAG_SCAN_4X4` exactly, so `coeffs[sb*16 + k]` indexing is consistent
/// across all TU sizes.
#[rustfmt::skip]
pub(crate) static ZIGZAG_16X16: [(usize, usize); 256] = [
    (0,0),(1,0),(0,1),(2,0),(1,1),(0,2),(3,0),(2,1),
    (1,2),(0,3),(3,1),(2,2),(1,3),(3,2),(2,3),(3,3),
    (4,0),(5,0),(4,1),(6,0),(5,1),(4,2),(7,0),(6,1),
    (5,2),(4,3),(7,1),(6,2),(5,3),(7,2),(6,3),(7,3),
    (0,4),(1,4),(0,5),(2,4),(1,5),(0,6),(3,4),(2,5),
    (1,6),(0,7),(3,5),(2,6),(1,7),(3,6),(2,7),(3,7),
    (8,0),(9,0),(8,1),(10,0),(9,1),(8,2),(11,0),(10,1),
    (9,2),(8,3),(11,1),(10,2),(9,3),(11,2),(10,3),(11,3),
    (4,4),(5,4),(4,5),(6,4),(5,5),(4,6),(7,4),(6,5),
    (5,6),(4,7),(7,5),(6,6),(5,7),(7,6),(6,7),(7,7),
    (0,8),(1,8),(0,9),(2,8),(1,9),(0,10),(3,8),(2,9),
    (1,10),(0,11),(3,9),(2,10),(1,11),(3,10),(2,11),(3,11),
    (12,0),(13,0),(12,1),(14,0),(13,1),(12,2),(15,0),(14,1),
    (13,2),(12,3),(15,1),(14,2),(13,3),(15,2),(14,3),(15,3),
    (8,4),(9,4),(8,5),(10,4),(9,5),(8,6),(11,4),(10,5),
    (9,6),(8,7),(11,5),(10,6),(9,7),(11,6),(10,7),(11,7),
    (4,8),(5,8),(4,9),(6,8),(5,9),(4,10),(7,8),(6,9),
    (5,10),(4,11),(7,9),(6,10),(5,11),(7,10),(6,11),(7,11),
    (0,12),(1,12),(0,13),(2,12),(1,13),(0,14),(3,12),(2,13),
    (1,14),(0,15),(3,13),(2,14),(1,15),(3,14),(2,15),(3,15),
    (12,4),(13,4),(12,5),(14,4),(13,5),(12,6),(15,4),(14,5),
    (13,6),(12,7),(15,5),(14,6),(13,7),(15,6),(14,7),(15,7),
    (8,8),(9,8),(8,9),(10,8),(9,9),(8,10),(11,8),(10,9),
    (9,10),(8,11),(11,9),(10,10),(9,11),(11,10),(10,11),(11,11),
    (4,12),(5,12),(4,13),(6,12),(5,13),(4,14),(7,12),(6,13),
    (5,14),(4,15),(7,13),(6,14),(5,15),(7,14),(6,15),(7,15),
    (12,8),(13,8),(12,9),(14,8),(13,9),(12,10),(15,8),(14,9),
    (13,10),(12,11),(15,9),(14,10),(13,11),(15,10),(14,11),(15,11),
    (8,12),(9,12),(8,13),(10,12),(9,13),(8,14),(11,12),(10,13),
    (9,14),(8,15),(11,13),(10,14),(9,15),(11,14),(10,15),(11,15),
    (12,12),(13,12),(12,13),(14,12),(13,13),(12,14),(15,12),(14,13),
    (13,14),(12,15),(15,13),(14,14),(13,15),(15,14),(14,15),(15,15),
];
